- hosts: all
  tasks:
  - name: Update Packages
    become: true
    become_user: ansible
    become_method: sudo
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 #One day
